import { TranslationServiceClient } from '@google-cloud/translate';

const translationClient = new TranslationServiceClient({
  credentials: {
    client_email: process.env.GOOGLE_TRANSLATE_CLIENT_EMAIL,
    private_key: process.env.GOOGLE_TRANSLATE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
  },
  projectId: process.env.GOOGLE_TRANSLATE_PROJECT_ID,
});

const projectId = process.env.GOOGLE_TRANSLATE_PROJECT_ID!;
const location = 'global';

export type Labels = {
  reference: string;
  nutritionalInfo: string;
  additionalDetails: string;
  name: string;
  eanCode: string;
  foodName: string;
  foodType: string;
  ingredients: string;
  netQuantity: string;
  alcohol: string;
  energyValue: string;
  fats: string;
  saturatedFats: string;
  carbohydrates: string;
  sugars: string;
  proteins: string;
  salt: string;
  countryOfOrigin: string;
  placeOfOrigin: string;
  productionVariants: string;
  certifications: string;
  instructionsForUse: string;
  conservationConditions: string;
  serviceConditions: string;
  drainedWeight: string;
  operatorData: string;
  operatorName: string;
  operatorAddress: string;
  registration: string;
  grams: string;
  centiliters: string;
  optionalLabelling: string;
  recyclableComponents: string;
  glassBottle: string;
  aluminumCap: string;
  cardboardBox: string;
  corkStopper: string;
  glassContainer: string;
  yellowContainer: string;
  blueContainer: string;
  brownContainer: string;
}

export async function translateText(text: string, targetLanguage: string) {
  if (targetLanguage === 'es') return text;
  
  try {
    const request = {
      parent: `projects/${projectId}/locations/${location}`,
      contents: [text],
      mimeType: 'text/plain',
      sourceLanguageCode: 'es',
      targetLanguageCode: targetLanguage,
    };

    const [response] = await translationClient.translateText(request);
    return response.translations?.[0]?.translatedText || text;
  } catch (error: any) {
    // Log the error but don't show it to the user
    console.error('Translation error:', error);
    
    // For quota errors, we can implement a fallback or retry mechanism
    if (error.code === 8) { // RESOURCE_EXHAUSTED
      console.log('Translation quota exceeded, using original text');
    }
    
    // Return the original text if translation fails
    return text;
  }
}

export async function translateWine(wine: any, targetLanguage: string) {
  if (targetLanguage === 'es') return wine;

  const translatedWine = { ...wine };

  // Translate basic fields except for specific ones
  // Do not translate: name, operatorName, placeOfOrigin, operatorAddress
  translatedWine.foodName = await translateText(wine.foodName, targetLanguage);
  if (wine.instructionsForUse) {
    translatedWine.instructionsForUse = await translateText(wine.instructionsForUse, targetLanguage);
  }
  if (wine.conservationConditions) {
    translatedWine.conservationConditions = await translateText(wine.conservationConditions, targetLanguage);
  }
  translatedWine.countryOfOrigin = await translateText(wine.countryOfOrigin, targetLanguage);
  if (wine.wineryInformation) {
    translatedWine.wineryInformation = await translateText(wine.wineryInformation, targetLanguage);
  }
  if (wine.serviceConditions) {
    translatedWine.serviceConditions = await translateText(wine.serviceConditions, targetLanguage);
  }
  if (wine.foodType) {
    translatedWine.foodType = await translateText(wine.foodType, targetLanguage);
  }

  // Translate ingredients
  if (wine.ingredients?.length > 0) {
    translatedWine.ingredients = await Promise.all(
      wine.ingredients.map(async (ingredient: any) => ({
        ...ingredient,
        name: await translateText(ingredient.name, targetLanguage),
      }))
    );
  }

  // Translate production variants
  if (wine.productionVariants?.length > 0) {
    translatedWine.productionVariants = await Promise.all(
      wine.productionVariants.map(async (variant: any) => ({
        ...variant,
        variantName: await translateText(variant.variantName, targetLanguage),
      }))
    );
  }

  // Translate certifications
  if (wine.certifications?.length > 0) {
    translatedWine.certifications = await Promise.all(
      wine.certifications.map(async (cert: any) => {
        if (typeof cert === 'string') {
          return await translateText(cert, targetLanguage);
        }
        return {
          ...cert,
          certificationName: await translateText(cert.certificationName, targetLanguage),
          description: cert.description ? await translateText(cert.description, targetLanguage) : undefined
        };
      })
    );
  }

  return translatedWine;
}

// Add translations for UI labels
export const uiLabels: Record<string, Labels> = {
  es: {
    reference: 'Referencia',
    nutritionalInfo: 'Información nutricional',
    additionalDetails: 'Detalles adicionales',
    name: 'Nombre',
    eanCode: 'Código EAN',
    foodName: 'Nombre del alimento',
    foodType: 'Tipo de alimento',
    ingredients: 'Ingredientes',
    netQuantity: 'Cantidad neta',
    alcohol: 'Alcohol',
    energyValue: 'Valor energético',
    fats: 'Grasas',
    saturatedFats: 'Grasas saturadas',
    carbohydrates: 'Carbohidratos',
    sugars: 'Azúcares',
    proteins: 'Proteínas',
    salt: 'Sal',
    countryOfOrigin: 'País de origen',
    placeOfOrigin: 'Lugar de origen',
    productionVariants: 'Variantes de producción',
    certifications: 'Certificaciones',
    instructionsForUse: 'Instrucciones de uso',
    conservationConditions: 'Condiciones de conservación',
    serviceConditions: 'Condiciones de servicio',
    drainedWeight: 'Peso escurrido',
    operatorData: 'Datos del operador',
    operatorName: 'Nombre del operador',
    operatorAddress: 'Dirección del operador',
    registration: 'Registro',
    grams: 'gramos',
    centiliters: 'centilitros',
    optionalLabelling: 'Menciones obligatorias o facultativas',
    recyclableComponents: 'Componentes reciclables',
    glassBottle: 'Botella: vidrio',
    aluminumCap: 'Tapón: aluminio',
    cardboardBox: 'Caja: cartón',
    corkStopper: 'Tapón: corcho',
    glassContainer: 'contenedor de vidrio',
    yellowContainer: 'contenedor amarillo',
    blueContainer: 'contenedor azul',
    brownContainer: 'contenedor marrón'
  },
  en: {
    reference: 'Reference',
    nutritionalInfo: 'Nutritional Information',
    additionalDetails: 'Additional Details',
    name: 'Name',
    eanCode: 'EAN Code',
    foodName: 'Food Name',
    foodType: 'Food Type',
    ingredients: 'Ingredients',
    netQuantity: 'Net Quantity',
    alcohol: 'Alcohol',
    energyValue: 'Energy Value',
    fats: 'Fats',
    saturatedFats: 'Saturated Fats',
    carbohydrates: 'Carbohydrates',
    sugars: 'Sugars',
    proteins: 'Proteins',
    salt: 'Salt',
    countryOfOrigin: 'Country of Origin',
    placeOfOrigin: 'Place of Origin',
    productionVariants: 'Production Variants',
    certifications: 'Certifications',
    instructionsForUse: 'Instructions for Use',
    conservationConditions: 'Conservation Conditions',
    serviceConditions: 'Service Conditions',
    drainedWeight: 'Drained Weight',
    operatorData: 'Operator Data',
    operatorName: 'Operator Name',
    operatorAddress: 'Operator Address',
    registration: 'Registration',
    grams: 'grams',
    centiliters: 'centiliters',
    optionalLabelling: 'Mandatory or optional mentions',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Bottle: glass',
    aluminumCap: 'Cap: aluminum',
    cardboardBox: 'Box: cardboard',
    corkStopper: 'Stopper: cork',
    glassContainer: 'glass container',
    yellowContainer: 'yellow container',
    blueContainer: 'blue container',
    brownContainer: 'brown container'
  },
  fr: {
    reference: 'Référence',
    nutritionalInfo: 'Information Nutritionnelle',
    additionalDetails: 'Détails Supplémentaires',
    name: 'Nom',
    eanCode: 'Code EAN',
    foodName: 'Nom de l\'aliment',
    foodType: 'Type d\'aliment',
    ingredients: 'Ingrédients',
    netQuantity: 'Quantité Nette',
    alcohol: 'Alcool',
    energyValue: 'Valeur Énergétique',
    fats: 'Matières grasses',
    saturatedFats: 'Acides gras saturés',
    carbohydrates: 'Glucides',
    sugars: 'Sucres',
    proteins: 'Protéines',
    salt: 'Sel',
    countryOfOrigin: 'Pays d\'origine',
    placeOfOrigin: 'Lieu d\'origine',
    productionVariants: 'Variantes de Production',
    certifications: 'Certifications',
    instructionsForUse: 'Mode d\'emploi',
    conservationConditions: 'Conditions de Conservation',
    serviceConditions: 'Conditions de Service',
    drainedWeight: 'Poids égoutté',
    operatorData: 'Données de l\'opérateur',
    operatorName: 'Nom de l\'opérateur',
    operatorAddress: 'Adresse de l\'opérateur',
    registration: 'Enregistrement',
    grams: 'grammes',
    centiliters: 'centilitres',
    optionalLabelling: 'Mention obligatoire ou facultative',
    recyclableComponents: 'Composants Recyclables',
    glassBottle: 'Bouteille: verre',
    aluminumCap: 'Bouchon: aluminium',
    cardboardBox: 'Boîte: carton',
    corkStopper: 'Bouchon: liège',
    glassContainer: 'conteneur à verre',
    yellowContainer: 'conteneur jaune',
    blueContainer: 'conteneur bleu',
    brownContainer: 'conteneur marron'
  },
  de: {
    reference: 'Referenz',
    nutritionalInfo: 'Nährwertinformationen',
    additionalDetails: 'Zusätzliche Details',
    name: 'Name',
    eanCode: 'EAN-Code',
    foodName: 'Lebensmittelname',
    foodType: 'Lebensmitteltyp',
    ingredients: 'Zutaten',
    netQuantity: 'Nettomenge',
    alcohol: 'Alkohol',
    energyValue: 'Energiewert',
    fats: 'Fette',
    saturatedFats: 'Gesättigte Fettsäuren',
    carbohydrates: 'Kohlenhydrate',
    sugars: 'Zucker',
    proteins: 'Proteine',
    salt: 'Salz',
    countryOfOrigin: 'Herkunftsland',
    placeOfOrigin: 'Herkunftsort',
    productionVariants: 'Produktionsvarianten',
    certifications: 'Zertifizierungen',
    instructionsForUse: 'Gebrauchsanweisung',
    conservationConditions: 'Aufbewahrungsbedingungen',
    serviceConditions: 'Lagerungsbedingungen',
    drainedWeight: 'Abtropfgewicht',
    operatorData: 'Betreiberdaten',
    operatorName: 'Name des Betreibers',
    operatorAddress: 'Adresse des Betreibers',
    registration: 'Registrierung',
    grams: 'Gramm',
    centiliters: 'Zentiliter',
    optionalLabelling: 'Pflicht- oder Optionalangaben',
    recyclableComponents: 'Recyclingfähige Komponenten',
    glassBottle: 'Glasflasche',
    aluminumCap: 'Kork',
    cardboardBox: 'Karton',
    corkStopper: 'Kork',
    glassContainer: 'Glasbehälter',
    yellowContainer: 'Gelber Container',
    blueContainer: 'Blauer Container',
    brownContainer: 'Brauner Container'
  },
  it: {
    reference: 'Riferimento',
    nutritionalInfo: 'Informazioni Nutrizionali',
    additionalDetails: 'Dettagli Aggiuntivi',
    name: 'Nome',
    eanCode: 'Codice EAN',
    foodName: 'Nome dell\'alimento',
    foodType: 'Tipo di alimento',
    ingredients: 'Ingredienti',
    netQuantity: 'Quantità Netta',
    alcohol: 'Alcol',
    energyValue: 'Valore Energetico',
    fats: 'Grassi',
    saturatedFats: 'Acidi grassi saturi',
    carbohydrates: 'Carboidrati',
    sugars: 'Zuccheri',
    proteins: 'Proteine',
    salt: 'Sale',
    countryOfOrigin: 'Paese di origine',
    placeOfOrigin: 'Luogo di origine',
    productionVariants: 'Varianti di Produzione',
    certifications: 'Certificazioni',
    instructionsForUse: 'Istruzioni per l\'uso',
    conservationConditions: 'Condizioni di Conservazione',
    serviceConditions: 'Condizioni di Servizio',
    drainedWeight: 'Peso sgocciolato',
    operatorData: 'Dati dell\'operatore',
    operatorName: 'Nome dell\'operatore',
    operatorAddress: 'Indirizzo dell\'operatore',
    registration: 'Registrazione',
    grams: 'grammi',
    centiliters: 'centilitri',
    optionalLabelling: 'Mentioni obbligatorie o facoltativi',
    recyclableComponents: 'Componenti Recyclable',
    glassBottle: 'Bottiglia di vetro',
    aluminumCap: 'Tappo',
    cardboardBox: 'Scatola di cartone',
    corkStopper: 'Tappo',
    glassContainer: 'Contenitore di vetro',
    yellowContainer: 'Contenitore giallo',
    blueContainer: 'Contenitore blu',
    brownContainer: 'Contenitore marrone'
  },
  ca: {
    reference: 'Referència',
    nutritionalInfo: 'Informació nutricional',
    additionalDetails: 'Detalls addicionals',
    name: 'Nom',
    eanCode: 'Codi EAN',
    foodName: 'Nom de l\'aliment',
    foodType: 'Tipus d\'aliment',
    ingredients: 'Ingredients',
    netQuantity: 'Quantitat neta',
    alcohol: 'Alcohol',
    energyValue: 'Valor energètic',
    fats: 'Greixos',
    saturatedFats: 'Greixos saturats',
    carbohydrates: 'Hidrats de carboni',
    sugars: 'Sucres',
    proteins: 'Proteïnes',
    salt: 'Sal',
    countryOfOrigin: 'País d\'origen',
    placeOfOrigin: 'Lloc d\'origen',
    productionVariants: 'Variants de producció',
    certifications: 'Certificacions',
    instructionsForUse: 'Instruccions d\'ús',
    conservationConditions: 'Condicions de conservació',
    serviceConditions: 'Condicions de servei',
    drainedWeight: 'Pes escorregut',
    operatorData: 'Dades de l\'operador',
    operatorName: 'Nom de l\'operador',
    operatorAddress: 'Adreça de l\'operador',
    registration: 'Registre',
    grams: 'grams',
    centiliters: 'centilitres',
    optionalLabelling: 'Mencions obligatòries o facultatives',
    recyclableComponents: 'Components Recyclables',
    glassBottle: 'Ampolla de vidre',
    aluminumCap: 'Tapa',
    cardboardBox: 'Caixa de cartó',
    corkStopper: 'Tapa',
    glassContainer: 'Recipiente de vidre',
    yellowContainer: 'Recipiente groc',
    blueContainer: 'Recipiente blau',
    brownContainer: 'Recipiente marró'
  },
  gl: {
    reference: 'Referencia',
    nutritionalInfo: 'Información nutricional',
    additionalDetails: 'Detalles adicionais',
    name: 'Nome',
    eanCode: 'Código EAN',
    foodName: 'Nome do alimento',
    foodType: 'Tipo de alimento',
    ingredients: 'Ingredientes',
    netQuantity: 'Cantidade neta',
    alcohol: 'Alcohol',
    energyValue: 'Valor enerxético',
    fats: 'Graxas',
    saturatedFats: 'Graxas saturadas',
    carbohydrates: 'Hidratos de carbono',
    sugars: 'Azucres',
    proteins: 'Proteínas',
    salt: 'Sal',
    countryOfOrigin: 'País de orixe',
    placeOfOrigin: 'Lugar de orixe',
    productionVariants: 'Variantes de produción',
    certifications: 'Certificacións',
    instructionsForUse: 'Instrucións de uso',
    conservationConditions: 'Condicións de conservación',
    serviceConditions: 'Condicións de servizo',
    drainedWeight: 'Peso escorrido',
    operatorData: 'Datos do operador',
    operatorName: 'Nome do operador',
    operatorAddress: 'Enderezo do operador',
    registration: 'Rexistro',
    grams: 'gramos',
    centiliters: 'centilitros',
    optionalLabelling: 'Menciones obligatorias ou facultativas',
    recyclableComponents: 'Componentes Recyclables',
    glassBottle: 'Garrafa de vidro',
    aluminumCap: 'Capa',
    cardboardBox: 'Caixa de cartón',
    corkStopper: 'Capa',
    glassContainer: 'Recipiente de vidro',
    yellowContainer: 'Recipiente amarelo',
    blueContainer: 'Recipiente azul',
    brownContainer: 'Recipiente marron'
  },
  pt: {
    reference: 'Referência',
    nutritionalInfo: 'Informação nutricional',
    additionalDetails: 'Detalhes adicionais',
    name: 'Nome',
    eanCode: 'Código EAN',
    foodName: 'Nome do alimento',
    foodType: 'Tipo de alimento',
    ingredients: 'Ingredientes',
    netQuantity: 'Quantidade líquida',
    alcohol: 'Álcool',
    energyValue: 'Valor energético',
    fats: 'Gorduras',
    saturatedFats: 'Gorduras saturadas',
    carbohydrates: 'Hidratos de carbono',
    sugars: 'Açúcares',
    proteins: 'Proteínas',
    salt: 'Sal',
    countryOfOrigin: 'País de origem',
    placeOfOrigin: 'Local de origem',
    productionVariants: 'Variantes de produção',
    certifications: 'Certificações',
    instructionsForUse: 'Instruções de utilização',
    conservationConditions: 'Condições de conservação',
    serviceConditions: 'Condições de serviço',
    drainedWeight: 'Peso escorrido',
    operatorData: 'Dados do operador',
    operatorName: 'Nome do operador',
    operatorAddress: 'Endereço do operador',
    registration: 'Registo',
    grams: 'gramas',
    centiliters: 'centilitros',
    optionalLabelling: 'Menciones obrigatórias ou facultativas',
    recyclableComponents: 'Componentes Recyclables',
    glassBottle: 'Garrafa de vidro',
    aluminumCap: 'Tampa',
    cardboardBox: 'Caixa de cartão',
    corkStopper: 'Tampa',
    glassContainer: 'Recipiente de vidro',
    yellowContainer: 'Recipiente amarelo',
    blueContainer: 'Recipiente azul',
    brownContainer: 'Recipiente marrom'
  },
  ro: {
    reference: 'Referință',
    nutritionalInfo: 'Informații nutriționale',
    additionalDetails: 'Detalii suplimentare',
    name: 'Nume',
    eanCode: 'Cod EAN',
    foodName: 'Denumirea alimentului',
    foodType: 'Tipul alimentului',
    ingredients: 'Ingrediente',
    netQuantity: 'Cantitate netă',
    alcohol: 'Alcool',
    energyValue: 'Valoare energetică',
    fats: 'Grăsimi',
    saturatedFats: 'Acizi grași saturați',
    carbohydrates: 'Glucide',
    sugars: 'Zaharuri',
    proteins: 'Proteine',
    salt: 'Sare',
    countryOfOrigin: 'Țara de origine',
    placeOfOrigin: 'Locul de origine',
    productionVariants: 'Variante de producție',
    certifications: 'Certificări',
    instructionsForUse: 'Instrucțiuni de utilizare',
    conservationConditions: 'Condiții de conservare',
    serviceConditions: 'Condiții de servire',
    drainedWeight: 'Greutate scursă',
    operatorData: 'Date operator',
    operatorName: 'Numele operatorului',
    operatorAddress: 'Adresa operatorului',
    registration: 'Înregistrare',
    grams: 'grame',
    centiliters: 'centilitri',
    optionalLabelling: 'Mentionări obligatorii sau facultative',
    recyclableComponents: 'Componente Recyclable',
    glassBottle: 'Sticlă',
    aluminumCap: 'Tampon',
    cardboardBox: 'Cutie',
    corkStopper: 'Tampon',
    glassContainer: 'Recipient de sticlă',
    yellowContainer: 'Recipient galben',
    blueContainer: 'Recipient albastru',
    brownContainer: 'Recipient maron'
  },
  nl: {
    reference: 'Referentie',
    nutritionalInfo: 'Voedingswaarde-informatie',
    additionalDetails: 'Aanvullende details',
    name: 'Naam',
    eanCode: 'EAN-code',
    foodName: 'Naam van het levensmiddel',
    foodType: 'Voedingsmiddeltype',
    ingredients: 'Ingrediënten',
    netQuantity: 'Nettohoeveelheid',
    alcohol: 'Alcohol',
    energyValue: 'Energiewaarde',
    fats: 'Vetten',
    saturatedFats: 'Verzadigde vetzuren',
    carbohydrates: 'Koolhydraten',
    sugars: 'Suikers',
    proteins: 'Eiwitten',
    salt: 'Zout',
    countryOfOrigin: 'Land van oorsprong',
    placeOfOrigin: 'Plaats van oorsprong',
    productionVariants: 'Productievarianten',
    certifications: 'Certificeringen',
    instructionsForUse: 'Gebruiksaanwijzing',
    conservationConditions: 'Bewaaromstandigheden',
    serviceConditions: 'Bewaarcondities',
    drainedWeight: 'Uitlekgewicht',
    operatorData: 'Gegevens exploitant',
    operatorName: 'Naam exploitant',
    operatorAddress: 'Adres exploitant',
    registration: 'Registratie',
    grams: 'gram',
    centiliters: 'centiliter',
    optionalLabelling: 'Verplichte of optionele vermeldingen',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Glasfles',
    aluminumCap: 'Kork',
    cardboardBox: 'Karton',
    corkStopper: 'Kork',
    glassContainer: 'Glascontainer',
    yellowContainer: 'Gele container',
    blueContainer: 'Blauwe container',
    brownContainer: 'Bruine container'
  },
  sv: {
    reference: 'Referens',
    nutritionalInfo: 'Näringsinnehåll',
    additionalDetails: 'Ytterligare detaljer',
    name: 'Namn',
    eanCode: 'EAN-kod',
    foodName: 'Livsmedlets namn',
    foodType: 'Livsmedelstyp',
    ingredients: 'Ingredienser',
    netQuantity: 'Nettomängd',
    alcohol: 'Alkohol',
    energyValue: 'Energivärde',
    fats: 'Fett',
    saturatedFats: 'Mättat fett',
    carbohydrates: 'Kolhydrater',
    sugars: 'Sockerarter',
    proteins: 'Protein',
    salt: 'Salt',
    countryOfOrigin: 'Ursprungsland',
    placeOfOrigin: 'Ursprungsort',
    productionVariants: 'Produktionsvarianter',
    certifications: 'Certifieringar',
    instructionsForUse: 'Bruksanvisning',
    conservationConditions: 'Förvaringsvillkor',
    serviceConditions: 'Lageringsvillkor',
    drainedWeight: 'Avrunnen vikt',
    operatorData: 'Operatörsdata',
    operatorName: 'Operatörens namn',
    operatorAddress: 'Operatörens adress',
    registration: 'Registrering',
    grams: 'gram',
    centiliters: 'centiliter',
    optionalLabelling: 'Obligatoriska eller valfria anteckningar',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Glasflaska',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartong',
    corkStopper: 'Kork',
    glassContainer: 'Glasbehållare',
    yellowContainer: 'Gul behållare',
    blueContainer: 'Blå behållare',
    brownContainer: 'Brun behållare'
  },
  da: {
    reference: 'Reference',
    nutritionalInfo: 'Næringsindhold',
    additionalDetails: 'Yderligere detaljer',
    name: 'Navn',
    eanCode: 'EAN-kode',
    foodName: 'Fødevarens navn',
    foodType: 'Fødevaretype',
    ingredients: 'Ingredienser',
    netQuantity: 'Nettomængde',
    alcohol: 'Alkohol',
    energyValue: 'Energiværdi',
    fats: 'Fedt',
    saturatedFats: 'Mættet fedt',
    carbohydrates: 'Kulhydrater',
    sugars: 'Sukkerarter',
    proteins: 'Protein',
    salt: 'Salt',
    countryOfOrigin: 'Oprindelsesland',
    placeOfOrigin: 'Oprindelsessted',
    productionVariants: 'Produktionsvarianter',
    certifications: 'Certificeringer',
    instructionsForUse: 'Brugsanvisning',
    conservationConditions: 'Opbevaringsbetingelser',
    serviceConditions: 'Lageringsbetingelser',
    drainedWeight: 'Afvandet vægt',
    operatorData: 'Operatørdata',
    operatorName: 'Operatørens navn',
    operatorAddress: 'Operatørens adresse',
    registration: 'Registrering',
    grams: 'gram',
    centiliters: 'centiliter',
    optionalLabelling: 'Obligatoriske eller valgfrie bemærkninger',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Glasflaske',
    aluminumCap: 'Kork',
    cardboardBox: 'Karton',
    corkStopper: 'Kork',
    glassContainer: 'Glasbeholder',
    yellowContainer: 'Gul beholder',
    blueContainer: 'Blå beholder',
    brownContainer: 'Brun beholder'
  },
  bg: {
    reference: 'Референция',
    nutritionalInfo: 'Хранителна информация',
    additionalDetails: 'Допълнителни детайли',
    name: 'Име',
    eanCode: 'EAN код',
    foodName: 'Наименование на храната',
    foodType: 'Тип на храната',
    ingredients: 'Съставки',
    netQuantity: 'Нетно количество',
    alcohol: 'Алкохол',
    energyValue: 'Енергийна стойност',
    fats: 'Мазнини',
    saturatedFats: 'Наситени мастни киселини',
    carbohydrates: 'Въглехидрати',
    sugars: 'Захари',
    proteins: 'Белтъци',
    salt: 'Сол',
    countryOfOrigin: 'Страна на произход',
    placeOfOrigin: 'Място на произход',
    productionVariants: 'Производствени варианти',
    certifications: 'Сертификати',
    instructionsForUse: 'Инструкции за употреба',
    conservationConditions: 'Условия за съхранение',
    serviceConditions: 'Условия за съхранение',
    drainedWeight: 'Отцедено тегло',
    operatorData: 'Данни за оператора',
    operatorName: 'Име на оператора',
    operatorAddress: 'Адрес на оператора',
    registration: 'Регистрация',
    grams: 'грама',
    centiliters: 'сантилитра',
    optionalLabelling: 'Обязателни или факултативните споменавания',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Стъклена бутилка',
    aluminumCap: 'Корк',
    cardboardBox: 'Картонна кутия',
    corkStopper: 'Корк',
    glassContainer: 'Стъклен съд',
    yellowContainer: 'Жълт контейнер',
    blueContainer: 'Бял контейнер',
    brownContainer: 'Мортов контейнер'
  },
  cs: {
    reference: 'Reference',
    nutritionalInfo: 'Výživové údaje',
    additionalDetails: 'Další podrobnosti',
    name: 'Název',
    eanCode: 'EAN kód',
    foodName: 'Název potraviny',
    foodType: 'Potravinový typ',
    ingredients: 'Složení',
    netQuantity: 'Čisté množství',
    alcohol: 'Alkohol',
    energyValue: 'Energetická hodnota',
    fats: 'Tuky',
    saturatedFats: 'Nasycené mastné kyseliny',
    carbohydrates: 'Sacharidy',
    sugars: 'Cukry',
    proteins: 'Bílkoviny',
    salt: 'Sůl',
    countryOfOrigin: 'Země původu',
    placeOfOrigin: 'Místo původu',
    productionVariants: 'Výrobní varianty',
    certifications: 'Certifikace',
    instructionsForUse: 'Návod k použití',
    conservationConditions: 'Podmínky skladování',
    serviceConditions: 'Podmínky skladování',
    drainedWeight: 'Hmotnost po odkapání',
    operatorData: 'Údaje o provozovateli',
    operatorName: 'Jméno provozovatele',
    operatorAddress: 'Adresa provozovatele',
    registration: 'Registrace',
    grams: 'gramů',
    centiliters: 'centilitrů',
    optionalLabelling: 'Povinné nebo volitelné zmínky',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Skleněná lahev',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonová krabice',
    corkStopper: 'Kork',
    glassContainer: 'Skleněný obal',
    yellowContainer: 'Žlutý obal',
    blueContainer: 'Modrý obal',
    brownContainer: 'Hnědý obal'
  },
  sk: {
    reference: 'Referencia',
    nutritionalInfo: 'Výživové údaje',
    additionalDetails: 'Ďalšie podrobnosti',
    name: 'Názov',
    eanCode: 'EAN kód',
    foodName: 'Názov potraviny',
    foodType: 'Potravinový typ',
    ingredients: 'Zloženie',
    netQuantity: 'Čisté množstvo',
    alcohol: 'Alkohol',
    energyValue: 'Energetická hodnota',
    fats: 'Tuky',
    saturatedFats: 'Nasýtené mastné kyseliny',
    carbohydrates: 'Sacharidy',
    sugars: 'Cukry',
    proteins: 'Bielkoviny',
    salt: 'Soľ',
    countryOfOrigin: 'Krajina pôvodu',
    placeOfOrigin: 'Miesto pôvodu',
    productionVariants: 'Výrobné varianty',
    certifications: 'Certifikácie',
    instructionsForUse: 'Návod na použitie',
    conservationConditions: 'Podmienky skladovania',
    serviceConditions: 'Podmienky skladovania',
    drainedWeight: 'Hmotnosť po odkvapkaní',
    operatorData: 'Údaje o prevádzkovateľovi',
    operatorName: 'Meno prevádzkovateľa',
    operatorAddress: 'Adresa prevádzkovateľa',
    registration: 'Registrácia',
    grams: 'gramov',
    centiliters: 'centilitrov',
    optionalLabelling: 'Povinné alebo voliteľné poznámky',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Sklenená lahev',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonová krabica',
    corkStopper: 'Kork',
    glassContainer: 'Sklenený obal',
    yellowContainer: 'Žltý obal',
    blueContainer: 'Modrý obal',
    brownContainer: 'Hnědý obal'
  },
  sl: {
    reference: 'Referenca',
    nutritionalInfo: 'Hranilne vrednosti',
    additionalDetails: 'Dodatne podrobnosti',
    name: 'Ime',
    eanCode: 'EAN koda',
    foodName: 'Ime živila',
    foodType: 'Tip živila',
    ingredients: 'Sestavine',
    netQuantity: 'Neto količina',
    alcohol: 'Alkohol',
    energyValue: 'Energijska vrednost',
    fats: 'Maščobe',
    saturatedFats: 'Nasičene maščobe',
    carbohydrates: 'Ogljikovi hidrati',
    sugars: 'Sladkorji',
    proteins: 'Beljakovine',
    salt: 'Sol',
    countryOfOrigin: 'Država porekla',
    placeOfOrigin: 'Kraj porekla',
    productionVariants: 'Proizvodne variante',
    certifications: 'Certifikati',
    instructionsForUse: 'Navodila za uporabo',
    conservationConditions: 'Pogoji shranjevanja',
    serviceConditions: 'Pogoji shranjevanja',
    drainedWeight: 'Odcejena teža',
    operatorData: 'Podatki o nosilcu',
    operatorName: 'Ime nosilca',
    operatorAddress: 'Naslov nosilca',
    registration: 'Registracija',
    grams: 'gramov',
    centiliters: 'centilitrov',
    optionalLabelling: 'Povinjanje ali nepovpisanje',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Stakleni kozarec',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonasta kutija',
    corkStopper: 'Kork',
    glassContainer: 'Stakleni sprejemnik',
    yellowContainer: 'Rumeni sprejemnik',
    blueContainer: 'Modri sprejemnik',
    brownContainer: 'Rjavi sprejemnik'
  },
  hr: {
    reference: 'Referenca',
    nutritionalInfo: 'Hranjive vrijednosti',
    additionalDetails: 'Dodatni detalji',
    name: 'Naziv',
    eanCode: 'EAN kod',
    foodName: 'Naziv hrane',
    foodType: 'Tip hrane',
    ingredients: 'Sastojci',
    netQuantity: 'Neto količina',
    alcohol: 'Alkohol',
    energyValue: 'Energetska vrijednost',
    fats: 'Masti',
    saturatedFats: 'Zasićene masne kiseline',
    carbohydrates: 'Ugljikohidrati',
    sugars: 'Šećeri',
    proteins: 'Bjelančevine',
    salt: 'Sol',
    countryOfOrigin: 'Zemlja podrijetla',
    placeOfOrigin: 'Mjesto podrijetla',
    productionVariants: 'Proizvodne varijante',
    certifications: 'Certifikati',
    instructionsForUse: 'Upute za uporabu',
    conservationConditions: 'Uvjeti čuvanja',
    serviceConditions: 'Uvjeti čuvanja',
    drainedWeight: 'Ocijeđena masa',
    operatorData: 'Podaci o subjektu',
    operatorName: 'Ime subjekta',
    operatorAddress: 'Adresa subjekta',
    registration: 'Registracija',
    grams: 'grama',
    centiliters: 'centilitara',
    optionalLabelling: 'Obvezne oznake ali izbiranje',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Stakleni čaša',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonasta kutija',
    corkStopper: 'Kork',
    glassContainer: 'Stakleni sprejemnik',
    yellowContainer: 'Rumeni sprejemnik',
    blueContainer: 'Modri sprejemnik',
    brownContainer: 'Rjavi sprejemnik'
  },
  lv: {
    reference: 'Atsauce',
    nutritionalInfo: 'Uzturvērtība',
    additionalDetails: 'Papildu informācija',
    name: 'Nosaukums',
    eanCode: 'EAN kods',
    foodName: 'Pārtikas produkta nosaukums',
    foodType: 'Pārtikas produkta tips',
    ingredients: 'Sastāvdaļas',
    netQuantity: 'Neto daudzums',
    alcohol: 'Alkohols',
    energyValue: 'Enerģētiskā vērtība',
    fats: 'Tauki',
    saturatedFats: 'Piesātinātās taukskābes',
    carbohydrates: 'Ogļhidrātī',
    sugars: 'Cukuri',
    proteins: 'Olbaltumvielas',
    salt: 'Sāls',
    countryOfOrigin: 'Izcelsmes valsts',
    placeOfOrigin: 'Izcelsmes vieta',
    productionVariants: 'Ražošanas varianti',
    certifications: 'Sertifikāti',
    instructionsForUse: 'Lietošanas instrukcija',
    conservationConditions: 'Uzglabāšanas nosacījumi',
    serviceConditions: 'Uzglabāšanas nosacījumi',
    drainedWeight: 'Masa pēc notecināšanas',
    operatorData: 'Operatora dati',
    operatorName: 'Operatora nosaukums',
    operatorAddress: 'Operatora adrese',
    registration: 'Reģistrācija',
    grams: 'grami',
    centiliters: 'centilitri',
    optionalLabelling: 'Obligātie vai izvēlētie apzīmējumi',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Stakleni kozarec',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonāta kaste',
    corkStopper: 'Kork',
    glassContainer: 'Stakleni sprejemnis',
    yellowContainer: 'Dzeltenais sprejemnis',
    blueContainer: 'Zilāis sprejemnis',
    brownContainer: 'Brūnais sprejemnis'
  },
  lt: {
    reference: 'Nuoroda',
    nutritionalInfo: 'Maistinė vertė',
    additionalDetails: 'Papildoma informacija',
    name: 'Pavadinimas',
    eanCode: 'EAN kodas',
    foodName: 'Maisto produkto pavadinimas',
    foodType: 'Maisto produkto tipas',
    ingredients: 'Sudedamosios dalys',
    netQuantity: 'Grynasis kiekis',
    alcohol: 'Alkoholis',
    energyValue: 'Energinė vertė',
    fats: 'Riebalai',
    saturatedFats: 'Sočiosios riebalų rūgštys',
    carbohydrates: 'Angliavandeniai',
    sugars: 'Cukrūs',
    proteins: 'Baltymai',
    salt: 'Druska',
    countryOfOrigin: 'Kilmės šalis',
    placeOfOrigin: 'Kilmės vieta',
    productionVariants: 'Gamybos variantai',
    certifications: 'Sertifikatai',
    instructionsForUse: 'Vartojimo instrukcija',
    conservationConditions: 'Laikymo sąlygos',
    serviceConditions: 'Laikymo sąlygos',
    drainedWeight: 'Masė po nusausinimo',
    operatorData: 'Operatoriaus duomenys',
    operatorName: 'Operatoriaus pavadinimas',
    operatorAddress: 'Operatoriaus adresas',
    registration: 'Registracija',
    grams: 'gramai',
    centiliters: 'centilitrai',
    optionalLabelling: 'Obligatinės arba pasirinktinės žymėjimai',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Stakleni kozarec',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartoninė kibica',
    corkStopper: 'Kork',
    glassContainer: 'Staklinė indėlis',
    yellowContainer: 'Džiovinė indėlis',
    blueContainer: 'Mėlynė indėlis',
    brownContainer: 'Raudonė indėlis'
  },
  fi: {
    reference: 'Viite',
    nutritionalInfo: 'Ravintosisältö',
    additionalDetails: 'Lisätiedot',
    name: 'Nimi',
    eanCode: 'EAN-koodi',
    foodName: 'Elintarvikkeen nimi',
    foodType: 'Elintarvikkeen tyyppi',
    ingredients: 'Ainesosat',
    netQuantity: 'Sisällön määrä',
    alcohol: 'Alkoholi',
    energyValue: 'Energiasisältö',
    fats: 'Rasvat',
    saturatedFats: 'Tyydyttyneet rasvat',
    carbohydrates: 'Hiilihydraatit',
    sugars: 'Sokerit',
    proteins: 'Proteiinit',
    salt: 'Suola',
    countryOfOrigin: 'Alkuperämaa',
    placeOfOrigin: 'Alkuperäpaikka',
    productionVariants: 'Tuotantovariantit',
    certifications: 'Sertifikaatit',
    instructionsForUse: 'Käyttöohjeet',
    conservationConditions: 'Säilytysolosuhteet',
    serviceConditions: 'Säilytysolosuhteet',
    drainedWeight: 'Valutettu paino',
    operatorData: 'Toimijan tiedot',
    operatorName: 'Toimijan nimi',
    operatorAddress: 'Toimijan osoite',
    registration: 'Rekisteröinti',
    grams: 'grammaa',
    centiliters: 'senttilitraa',
    optionalLabelling: 'Pakolliset tai valinnaiset merkinnät',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Lasikuppi',
    aluminumCap: 'Korkki',
    cardboardBox: 'Kartonkuppi',
    corkStopper: 'Korkki',
    glassContainer: 'Lasikontti',
    yellowContainer: 'Keltaiset kontit',
    blueContainer: 'Vihreät kontit',
    brownContainer: 'Ruskea kontti'
  },
  et: {
    reference: 'Viide',
    nutritionalInfo: 'Toitumisalane teave',
    additionalDetails: 'Lisaandmed',
    name: 'Nimi',
    eanCode: 'EAN-kood',
    foodName: 'Toidu nimetus',
    foodType: 'Toidu liik',
    ingredients: 'Koostisosad',
    netQuantity: 'Netokogus',
    alcohol: 'Alkohol',
    energyValue: 'Energiasisaldus',
    fats: 'Rasvad',
    saturatedFats: 'Küllastunud rasvhapped',
    carbohydrates: 'Süsivesikud',
    sugars: 'Suhkrud',
    proteins: 'Valgud',
    salt: 'Sool',
    countryOfOrigin: 'Päritoluriik',
    placeOfOrigin: 'Päritolukoht',
    productionVariants: 'Tootmisvariandid',
    certifications: 'Sertifikaadid',
    instructionsForUse: 'Kasutusjuhend',
    conservationConditions: 'Säilitamistingimused',
    serviceConditions: 'Säilitamistingimused',
    drainedWeight: 'Nõrutatud kaal',
    operatorData: 'Käitleja andmed',
    operatorName: 'Käitleja nimi',
    operatorAddress: 'Käitleja aadress',
    registration: 'Registreerimine',
    grams: 'grammi',
    centiliters: 'sentiliitrit',
    optionalLabelling: 'Nõutavad või valikulised märkused',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Klaasikott',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonekott',
    corkStopper: 'Kork',
    glassContainer: 'Klaasikast',
    yellowContainer: 'Kollane kast',
    blueContainer: 'Sinine kast',
    brownContainer: 'Punane kast'
  },
  hu: {
    reference: 'Hivatkozás',
    nutritionalInfo: 'Tápértékadatok',
    additionalDetails: 'További részletek',
    name: 'Név',
    eanCode: 'EAN-kód',
    foodName: 'Élelmiszer megnevezése',
    foodType: 'Élelmiszer típusa',
    ingredients: 'Összetevők',
    netQuantity: 'Nettó mennyiség',
    alcohol: 'Alkohol',
    energyValue: 'Energiatartalom',
    fats: 'Zsír',
    saturatedFats: 'Telített zsírsavak',
    carbohydrates: 'Szénhidrát',
    sugars: 'Cukrok',
    proteins: 'Fehérje',
    salt: 'Só',
    countryOfOrigin: 'Származási ország',
    placeOfOrigin: 'Származási hely',
    productionVariants: 'Gyártási változatok',
    certifications: 'Tanúsítványok',
    instructionsForUse: 'Használati útmutató',
    conservationConditions: 'Tárolási feltételek',
    serviceConditions: 'Tárolási feltételek',
    drainedWeight: 'Töltőtömeg',
    operatorData: 'Üzemeltető adatai',
    operatorName: 'Üzemeltető neve',
    operatorAddress: 'Üzemeltető címe',
    registration: 'Nyilvántartás',
    grams: 'gramm',
    centiliters: 'centiliter',
    optionalLabelling: 'Kötelező vagy opcionális megjegyzések',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Üvegpalack',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonkés',
    corkStopper: 'Kork',
    glassContainer: 'Üvegtartály',
    yellowContainer: 'Sárga tartály',
    blueContainer: 'Kék tartály',
    brownContainer: 'Rózsaszín tartály'
  },
  ga: {
    reference: 'Tagairt',
    nutritionalInfo: 'Faisnéis chothaitheach',
    additionalDetails: 'Sonraí breise',
    name: 'Ainm',
    eanCode: 'Cód EAN',
    foodName: 'Ainm an bhia',
    foodType: 'Ainm an bhia',
    ingredients: 'Comhábhair',
    netQuantity: 'Glanmhéid',
    alcohol: 'Alcól',
    energyValue: 'Luach fuinnimh',
    fats: 'Saillte',
    saturatedFats: 'Saillte sáithithe',
    carbohydrates: 'Carbaihiodráití',
    sugars: 'Siúcraí',
    proteins: 'Próitéiní',
    salt: 'Salann',
    countryOfOrigin: 'Tír thionscnaimh',
    placeOfOrigin: 'Áit thionscnaimh',
    productionVariants: 'Leaganacha táirgthe',
    certifications: 'Deimhnithe',
    instructionsForUse: 'Treoracha úsáide',
    conservationConditions: 'Coinníollacha caomhnaithe',
    serviceConditions: 'Coinníollacha caomhnaithe',
    drainedWeight: 'Meáchan draenáilte',
    operatorData: 'Sonraí an oibreora',
    operatorName: 'Ainm an oibreora',
    operatorAddress: 'Seoladh an oibreora',
    registration: 'Clárú',
    grams: 'gram',
    centiliters: 'ceintilítear',
    optionalLabelling: 'Mentiones obrigatórias ou facultativas',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Glasflaska',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonkuppi',
    corkStopper: 'Kork',
    glassContainer: 'Glasbeholder',
    yellowContainer: 'Gelb',
    blueContainer: 'Blá',
    brownContainer: 'Brú'
  },
  mt: {
    reference: 'Referenza',
    nutritionalInfo: 'Informazzjoni dwar in-nutrizzjoni',
    additionalDetails: 'Dettalji addizzjonali',
    name: 'Isem',
    eanCode: 'Kodiċi EAN',
    foodName: 'Isem tal-ikel',
    foodType: 'Isem tal-ikel',
    ingredients: 'Ingredjenti',
    netQuantity: 'Kwantità netta',
    alcohol: 'Alkoħol',
    energyValue: 'Valur enerġetiku',
    fats: 'Xaħmijiet',
    saturatedFats: 'Xaħmijiet saturati',
    carbohydrates: 'Karboidrati',
    sugars: 'Zokkor',
    proteins: 'Proteini',
    salt: 'Melħ',
    countryOfOrigin: 'Pajjiż tal-oriġini',
    placeOfOrigin: 'Post tal-oriġini',
    productionVariants: 'Varjanti tal-produzzjoni',
    certifications: 'Ċertifikazzjonijiet',
    instructionsForUse: 'Struzzjonijiet għall-użu',
    conservationConditions: 'Kundizzjonijiet ta\' konservazzjoni',
    serviceConditions: 'Kundizzjonijiet ta\' konservazzjoni',
    drainedWeight: 'Piż imnixxef',
    operatorData: 'Data tal-operatur',
    operatorName: 'Isem l-operatur',
    operatorAddress: 'Indirizz tal-operatur',
    registration: 'Reġistrazzjoni',
    grams: 'grammi',
    centiliters: 'ċentilitri',
    optionalLabelling: 'Mentionijiet obbligatori jew opzionali',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Glasflaska',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonkés',
    corkStopper: 'Kork',
    glassContainer: 'Glasbeholder',
    yellowContainer: 'Gelb',
    blueContainer: 'Blá',
    brownContainer: 'Brú'
  },
  el: {
    reference: 'Αναφορά',
    nutritionalInfo: 'Διατροφικές πληροφορίες',
    additionalDetails: 'Πρόσθετες λεπτομέρειες',
    name: 'Όνομα',
    eanCode: 'Κωδικός EAN',
    foodName: 'Ονομασία τροφίμου',
    foodType: 'Τύπος τροφίμου',
    ingredients: 'Συστατικά',
    netQuantity: 'Καθαρή ποσότητα',
    alcohol: 'Αλκοόλ',
    energyValue: 'Ενεργειακή αξία',
    fats: 'Λιπαρά',
    saturatedFats: 'Κορεσμένα λιπαρά',
    carbohydrates: 'Υδατάνθρακες',
    sugars: 'Σάκχαρα',
    proteins: 'Πρωτεΐνες',
    salt: 'Αλάτι',
    countryOfOrigin: 'Χώρα προέλευσης',
    placeOfOrigin: 'Τόπος προέλευσης',
    productionVariants: 'Παραλλαγές παραγωγής',
    certifications: 'Πιστοποιήσεις',
    instructionsForUse: 'Οδηγίες χρήσης',
    conservationConditions: 'Συνθήκες διατήρησης',
    serviceConditions: 'Συνθήκες διατήρησης',
    drainedWeight: 'Στραγγισμένο βάρος',
    operatorData: 'Στοιχεία υπευθύνου',
    operatorName: 'Όνομα υπευθύνου',
    operatorAddress: 'Διεύθυνση υπευθύνου',
    registration: 'Καταχώριση',
    grams: 'γραμμάρια',
    centiliters: 'εκατοστόλιτρα',
    optionalLabelling: 'Προαιρετικές ή υποχρεωτικές αναφορές',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Ποτήρι',
    aluminumCap: 'Καπάκι',
    cardboardBox: 'Καρτόνιο',
    corkStopper: 'Καπάκι',
    glassContainer: 'Ποτήρι',
    yellowContainer: 'Κίτρινο ποτήρι',
    blueContainer: 'Μπλε ποτήρι',
    brownContainer: 'Καφέ ποτήρι'
  },
  eu: {
    reference: 'Erreferentzia',
    nutritionalInfo: 'Nutrizio informazioa',
    additionalDetails: 'Xehetasun gehigarriak',
    name: 'Izena',
    eanCode: 'EAN kodea',
    foodName: 'Elikagaiaren izena',
    foodType: 'Elikagaiaren tipoa',
    ingredients: 'Osagaiak',
    netQuantity: 'Kantitate garbia',
    alcohol: 'Alkohola',
    energyValue: 'Energia balioa',
    fats: 'Koipeak',
    saturatedFats: 'Gantz aseak',
    carbohydrates: 'Karbohidratoak',
    sugars: 'Azukreak',
    proteins: 'Proteinak',
    salt: 'Gatza',
    countryOfOrigin: 'Jatorrizko herrialdea',
    placeOfOrigin: 'Jatorrizko tokia',
    productionVariants: 'Ekoizpen aldaerak',
    certifications: 'Ziurtagiriak',
    instructionsForUse: 'Erabilera argibideak',
    conservationConditions: 'Kontserbazio baldintzak',
    serviceConditions: 'Kontserbazio baldintzak',
    drainedWeight: 'Xukaturiko pisua',
    operatorData: 'Operadorearen datuak',
    operatorName: 'Operadorearen izena',
    operatorAddress: 'Operadorearen helbidea',
    registration: 'Erregistroa',
    grams: 'gramo',
    centiliters: 'zentilitro',
    optionalLabelling: 'Mentiones obligatorias ou facultativas',
    recyclableComponents: 'Recyclable Components',
    glassBottle: 'Glasflaska',
    aluminumCap: 'Kork',
    cardboardBox: 'Kartonkés',
    corkStopper: 'Kork',
    glassContainer: 'Glasbeholder',
    yellowContainer: 'Gelb',
    blueContainer: 'Blá',
    brownContainer: 'Brú'
  }
}; 